export const STUDENT_LOGIN_REQUEST = 'STUDENT_LOGIN_REQUEST'
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS'
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL'
export const STUDENT_LOGOUT = 'STUDENT_LOGOUT'

export const STUDENT_REGISTER_REQUEST = 'STUDENT_REGISTER_REQUEST'
export const STUDENT_REGISTER_SUCCESS = 'STUDENT_REGISTER_SUCCESS'
export const STUDENT_REGISTER_FAIL = 'STUDENT_REGISTER_FAIL'